kiwi-rikasa/ground-cow

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/meta.md, .github/PULL_REQUEST_TEMPLATE.md
=> chore: add templates

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/meta.md
=> chore: update templates

README.md
=> docs: add badge in readme

frontend/app/api/auth/[...nextauth]/route.ts, frontend/lib/auth.ts, frontend/vitest.config.ts
=> test(frontend): update frontend cov

README.md, frontend/vitest.config.ts
=> chore: remove auth from cov

backend/app/api/routes/__init__.py, backend/app/tests/test_main.py, backend/app/tests/test_router_event.py, backend/app/tests/test_router_report.py, backend/app/tests/test_router_zone.py
add tests for event, zone, report APIs.
Issue related: #17
=> test(backend): add tests for event, zone, report APIs

backend/app/api/routes/alert.py, backend/app/api/routes/earthquake.py, backend/app/api/routes/event.py, backend/app/api/routes/report.py, backend/app/api/routes/user.py
- GET /user/ filtered by user_role, default offset = 0, limit = 30
- GET /earthquake/ sorted by earthquake_occurred_at, default offset = 0, limit = 30
- GET /event/ filtered by zone_id, earthquake_id, event_severity, default sort by event_created_at, , default offset = 0, limit = 30
- GET /alert/ filtered by alert_state, zone_id, default sort by alert_created_at, default offset = 0 limit = 30
- GET /report/ filtered by alert_id, user_id, report_factory_zone, default sort by report_reported_at, default offset = 0 limit = 30
Issue: #36
=> feat(backend): add pagination, filtering, sorting to GET

README.md
update port for airflow web server
=> docs: update README.md for airflow port

.github/ISSUE_TEMPLATE/bug_report.md, frontend/app/(pages)/reports/page.tsx, frontend/app/alert.json, frontend/components/app-sidebar.tsx, frontend/components/nav-main.tsx
add tests for pagination, filter, sorting for user, earthquake, event, alert, report
Issue: #44
=> test(backend): add tests for pagination, filter, sorting

frontend/components/__test__/app-sidebar.test.tsx, frontend/components/__test__/data-table.test.tsx, frontend/components/__test__/login-form.test.tsx, frontend/components/__test__/nav-main.test.tsx, frontend/components/__test__/nav-secondary.test.tsx, frontend/components/__test__/nav-user.test.tsx, frontend/components/__test__/site-header.test.tsx, frontend/components/data-table.tsx, frontend/components/nav-user.tsx
Add unit test for self-implemented components including:
- `app-sidebar`
- `data-table`
- `login-form`
- `nav-main`
- `nav-secondary`
- `nav-user`
- `site-header`
=> test(frontend): add unit test for self-implemented components

frontend/app/(pages)/events/page.tsx, frontend/app/(pages)/reports/page.tsx, frontend/app/(pages)/team/page.tsx, frontend/app/alert.json, frontend/app/event-data.json, frontend/app/page.tsx, frontend/components/__test__/app-sidebar.test.tsx, frontend/components/alert-data-table.tsx, frontend/components/app-sidebar.tsx, frontend/components/event-data-table.tsx, frontend/components/ui/dropdown-menu.tsx, frontend/components/user-data-table.tsx
- add alert table in `home`
- add report table in `report`
- add event table in `event`
- add user table in `team`
=> feat(frontend): update 4 tables

.github/workflows/build.yml, backend/app/core/pre_start.py, backend/app/core/seed.py, docker-compose.yml
- pre-pr for add real seed
- add profile with backend
=> feat: add dummy seed script

airflow/dags/earthquake_fetcher_dag.py, airflow/dags/suppression_interval_fetcher_dag.py, airflow/dags/zone_fetcher_dag.py, airflow/utils/fetch_earthquake.py, airflow/utils/fetch_supression_interval.py, airflow/utils/fetch_zones.py, airflow/utils/parse_alert.py, airflow/utils/parse_earthquake.py, airflow/utils/parse_event.py, airflow/utils/save_alert.py, airflow/utils/save_earthquake.py, airflow/utils/save_event.py, docker-compose.yml
=> feat: airflow integration

frontend/app/(pages)/team/page.tsx
=> fix: team page

frontend/app/(pages)/page.tsx, frontend/components/alert-data-table.tsx, frontend/components/event-data-table.tsx, frontend/components/report-data-table.tsx
- fix modal field and wording
- fix `view details` action
- fix filter function
=> fix(frontend): fix table modal and actions

frontend/components/report-data-table.tsx, frontend/components/ui/alert.tsx
- Integrated backend API to support updating report details
- Added success and error alerts for update feedback
- Set minimum value constraint for the `Factory Zone` input field
=> fix(frontend): add report details updating

.github/workflows/build.yml, .github/workflows/test.yml, docker-compose.yml
=> chore: refine ci

frontend/components/nav-main.tsx, frontend/components/report-data-table.tsx
- Added `create report` dialog and alert
- Integrated API for report delete
- After deleting and creating reports, you need to refresh the page to update the data.
=> feat: implement report create and delete

airflow/README.md, airflow/src/config.py, airflow/src/data/alert_repository.py, airflow/src/data/equake_repository.py, airflow/src/data/event_repository.py, airflow/src/service/event_service.py
Added an environment variable that let users configure whether NA-severity events should be generated.
=> feat(airflow): add env var to control NA event generation

frontend/components/create-user-dialog.tsx, frontend/components/table/user-data-table.tsx
- Implement update user
- Implement update user with `create-user-dialog`
- Integrate API to delete user
=> feat(frontend): add and update user
